version: '3'
services:
  00_setup:
    #build: .
    image: registry.gitlab.com/supercash/core/haskell-stack-base:stack-2.7.3_haskell-8.10.7_13057207-master
    command: bash 
    #make -C 00_setup
    working_dir: /supercash/haskell
    volumes:
      - .:/supercash/haskell
  01_functions:
    build: .
    image: haskell101:latest
    command: make -C 01_functions
  02_datatypes:
    build: .
    image: haskell101:latest
    command: make -C 02_datatypes
  03_lists:
    build: .
    image: haskell101:latest
    command: make -C 03_lists
  04_abstractions:
    build: .
    image: haskell101:latest
    command: make -C 04_abstractions
  05_maybe:
    build: .
    image: haskell101:latest
    command: make -C 05_maybe
  06_rps:
    build: .
    image: haskell101:latest
    command: make -C 06_rps
    tty: true
